### ISSUE TITLE
Write better documentation on MCPE protocol

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/mcpe-server#2]

**Comment by mhsjlw** [comment]
:D https://github.com/mhsjlw/mcpe-protocol/blob/master/protocol/protocol.json

**Comment by Creeplays** [comment]
0x84 packet still needs to be decoded

**Comment by Creeplays** [comment]
Yay, got next packet and client crash! Thats better that nothing.

**Comment by mhsjlw** [comment]
@Creeplays Awesome!

**Comment by mhsjlw** [comment]
We're working on https://github.com/mhsjlw/pocket-minecraft-protocol and https://github.com/mhsjlw/node-raknet to make this process easier. This repository will be re-written.
